# Generated by Django 3.2.8 on 2021-10-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='127.0.0.1', max_length=50)),
                ('lat', models.CharField(default='0', max_length=50)),
                ('long', models.CharField(default='0', max_length=50)),
                ('user_agent', models.TextField(default='useragent')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
